/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MsSpinner {}
  interface MsSpinnerAttributes extends StencilHTMLAttributes {}

  interface MsStockFinder {}
  interface MsStockFinderAttributes extends StencilHTMLAttributes {
    'onMsSymbolSelected'?: (event: CustomEvent<string>) => void;
  }

  interface MsStockPrice {
    'stockSymbol': string;
  }
  interface MsStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MsSpinner': Components.MsSpinner;
    'MsStockFinder': Components.MsStockFinder;
    'MsStockPrice': Components.MsStockPrice;
  }

  interface StencilIntrinsicElements {
    'ms-spinner': Components.MsSpinnerAttributes;
    'ms-stock-finder': Components.MsStockFinderAttributes;
    'ms-stock-price': Components.MsStockPriceAttributes;
  }


  interface HTMLMsSpinnerElement extends Components.MsSpinner, HTMLStencilElement {}
  var HTMLMsSpinnerElement: {
    prototype: HTMLMsSpinnerElement;
    new (): HTMLMsSpinnerElement;
  };

  interface HTMLMsStockFinderElement extends Components.MsStockFinder, HTMLStencilElement {}
  var HTMLMsStockFinderElement: {
    prototype: HTMLMsStockFinderElement;
    new (): HTMLMsStockFinderElement;
  };

  interface HTMLMsStockPriceElement extends Components.MsStockPrice, HTMLStencilElement {}
  var HTMLMsStockPriceElement: {
    prototype: HTMLMsStockPriceElement;
    new (): HTMLMsStockPriceElement;
  };

  interface HTMLElementTagNameMap {
    'ms-spinner': HTMLMsSpinnerElement
    'ms-stock-finder': HTMLMsStockFinderElement
    'ms-stock-price': HTMLMsStockPriceElement
  }

  interface ElementTagNameMap {
    'ms-spinner': HTMLMsSpinnerElement;
    'ms-stock-finder': HTMLMsStockFinderElement;
    'ms-stock-price': HTMLMsStockPriceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
